### ISSUE TITLE
Need jQuery.offset() 

### ISSUE THREAD

**Issue by gpsarkar** [rpearsondev/CodedUI.jQueryExtensions#4]
Can we have a .offset() method in extension which would return the jQuery.offset() as a System.Drawing.Point() object.

**Comment by gpsarkar** [comment]
In continuation of my above issue, can we have some flexibility to send any jquery method as param along with the selectors. I found that .click() method very useful and we can pretty much avoid codedui's Mouse.Click(). Something like below, but method like ".click()" to be send as param or may be we can write wrapper many of these cool methods like offset(), click(), scrollTop(), etc.

        public static void JQueryClick(this BrowserWindow browserWindow, string selector)
        {
            if (string.IsNullOrWhiteSpace(selector))
            {
                throw new ArgumentException("selector");
            }

            EnsureJqueryInPage(browserWindow);

            browserWindow.ExecuteScript(string.Format("{0}.click()",
                    GetSelector(BrowserWindow.CurrentBrowser, selector)));
        }

**Comment by rpearsondev** [comment]
Sounds like a good idea, I will look into this.

**Comment by rpearsondev** [comment]
On reflection, this can be done other ways. I don't want to add to much to the JQuery Selectors unless they really add value.
