### ISSUE TITLE
getting error for selector - a:contains("text")

### ISSUE THREAD

**Issue by gpsarkar** [rpearsondev/CodedUI.jQueryExtensions#5]
Hello,

I am getting error for ":contains" selector. 

Example:
a:contains('Some Innertext')

Error:
Script execution failed. Script: return CodedUI.jQueryExtensions.jQuery('a:contains('Explore')')

**Comment by rpearsondev** [comment]
If you write it using escape characters it will work.

e.g
Browser.JQuerySelect<HtmlHyperlink>("a:contains(\"Explore\")");
