### ISSUE TITLE
System.InvalidCastException: One or more object(s) returned by the jQuery selector could not be cast....

### ISSUE THREAD

**Issue by sjdirect** [rpearsondev/CodedUI.jQueryExtensions#7]
Hi,

I'm regularly encountering exceptions like the following using version 1.0.4.1...

System.InvalidCastException: One or more object(s) returned by the jQuery selector could not be cast to HtmlHyperlink
Result1 StackTrace:	
at CodedUI.jQueryExtensions.JQueryExtensions.JQuerySelect[T](BrowserWindow browserWindow, String selector)
   at AVA.LMS.UiTests.StudentTest1.LoggedIn_CoursePlayer_HasUnitAndLessons() in d:\WorkRoot\Code\Agile\FLMS\AVA.LMS.UiTests\StudentTest1.cs:line 205

It seems like the css selectors below would only return the types I am trying to cast into. This happens with other types as well (HtmlSpan, HtmlDiv, etc..). Any reason why this would be happening? 

```
var example1 = browser.JQuerySelect<HtmlHyperlink>('a.class1');
var example2 = browser.JQuerySelect<HtmlListItem>('li.class2');
```
I can normally get around this by catching the exception and immediately retrying the same JQuerySelect statements above.

Thanks!!!

**Comment by sjdirect** [comment]
```
private HtmlSpan GetLoggedInStudentDisplayWithRetry(BrowserWindow browser)
{
	var attempts = 1;
	var exists = false;
	HtmlSpan target = null;
	while (!exists && attempts < MaxWaitRetryAttemps)
	{
		try
		{
			target = browser
				.JQuerySelect<HtmlSpan>("#headerSelectedStudent span")
				.SingleOrDefault(s => s.InnerText.Trim() == ValidUserStudent.DisplayName);
			exists = true;
		}
		catch (Exception e)
		{
			Console.WriteLine(e);
		}
		attempts++;
	}

	if (!exists || target == null || !target.Exists)
		throw new InvalidOperationException("Cound not find or cast value form #headerSelectedStudent span");

	return target;
}
```

**Comment by rpearsondev** [comment]
Is this happening on all browsers?

I am reviewing the integration tests to see if I can replicate.

**Comment by sjdirect** [comment]
I've only been using ie only. Thanks for checking.

**Comment by rpearsondev** [comment]
I have checked the select tests in all browsers and they are working, I would be useful if you could supply the mark-up that you are using the selectors on (the smallest failing subset).

**Comment by sjdirect** [comment]
Hi, i have uploaded some html markup that causes the error here...

https://gist.githubusercontent.com/sjdirect/624be502f69ba251319a/raw/a020c1cd4f5c2f9c36604158c4892b438c944c8e/CrashPage

When I run selectors like so...

var lessonsCssSelector = "#lessonactivitylist > li.leftNavLesson";
var lessons = browser.JQuerySelect<HtmlListItem>(lessonsCssSelector);

I get the errors most of the time. Its not specific to that page either. I'm able to set breakpoints before executing the select and directly using the browser console and jquery directly which selects exactly what is expected. 

Thanks!

**Comment by rpearsondev** [comment]
I cannot replicate this on a simple project. I suspect that this issue is specific to your application (something subtle). If this same issue is raised again, then I re-open this issue.
